### ISSUE TITLE
Missed elseif for status "full"

### ISSUE THREAD

**Issue by ckruczek** [koenwtje/awesome-batteryInfo#6]
Hey koentje,

there is an issue if the battery status is neither `Charging` nor `Discharging` but `Full`. The battery widget crashes when the last status is reached.

A solution would be to add this case:

``` lua
   elseif sta:match("Full") then
        icon = ""
        battery = ""
        percent = "Battery Full" 
    end
```

**Comment by koenw** [comment]
I totally for about this issue, sorry for the late reply! Looking at the code now, it should already be fixed. Thanks!
